<a href="https://colab.research.google.com/github/Pratichrs526/Pratichrs526/blob/main/Numpy_Lib's_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.sqrt(81)

9.0

In [5]:
ar= np.random.rand(2,3,5)
print(ar)

[[[0.16629986 0.23089832 0.92630738 0.95690358 0.62535175]
  [0.51394484 0.88803507 0.91008237 0.45612549 0.33777752]
  [0.52315895 0.95480615 0.02559397 0.62951845 0.534845  ]]

 [[0.10850004 0.28000371 0.16749623 0.5221976  0.39604807]
  [0.23782767 0.05479246 0.17442569 0.11043994 0.01990463]
  [0.23878827 0.34148311 0.00322585 0.28581509 0.94731715]]]


In [37]:
ar1= np.array([3,5])
print(ar1)
ar2= np.array([[4,16],[25,9]])
ar2
type(ar1)
ar2.dtype
ar2.shape
ar.shape
ar.size
ar2[1]
np.add(ar1,ar2)
np.dot(ar1,ar2)
np.sqrt(ar2)
np.power(12,2)
np.power(ar1,2)
np.sort(ar2)
np.sort(ar2)[::-1] #[start:stop:step]
np.delete(ar2,1,axis=0) #(array_name, row/column number, when axis=0 then row when axis=1 then column)

[3 5]


array([[ 4, 16]])

In [43]:
help(np.dot) #This is to get any help about any function from numpy lib. In Python, the help() function is a built-in function that provides information about modules, classes, functions, and modules.

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----